/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./../views/AboutView.vue')['default']
    AccountView: typeof import('./../views/AccountView.vue')['default']
    Close_icon: typeof import('./../components/icon/window_contorl/close_icon.vue')['default']
    DownloadsView: typeof import('./../views/DownloadsView.vue')['default']
    HomeView: typeof import('./../views/HomeView.vue')['default']
    Maximzie_icon: typeof import('./../components/icon/window_contorl/maximzie_icon.vue')['default']
    Minimzie_icon: typeof import('./../components/icon/window_contorl/minimzie_icon.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NFlex: typeof import('naive-ui')['NFlex']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    ProjectView: typeof import('./../views/ProjectView.vue')['default']
    Root_layout_header: typeof import('./../layout/root_layout_header.vue')['default']
    Root_layout_main: typeof import('./../layout/root_layout_main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingView: typeof import('./../views/SettingView.vue')['default']
    Sider_manu_downloads: typeof import('./../components/icon/sider_manu_downloads.vue')['default']
    Sider_menu_add: typeof import('./../components/icon/sider_menu_add.vue')['default']
    Sider_menu_gerenzhongxin: typeof import('./../components/icon/sider_menu_gerenzhongxin.vue')['default']
    Sider_menu_settings: typeof import('./../components/icon/sider_menu_settings.vue')['default']
    Sider_menu_xiangmu: typeof import('./../components/icon/sider_menu_xiangmu.vue')['default']
    Sider_meun_about: typeof import('./../components/icon/sider_meun_about.vue')['default']
    Sider_meun_fenlei: typeof import('./../components/icon/sider_meun_fenlei.vue')['default']
    Sider_meun_running: typeof import('./../components/icon/sider_meun_running.vue')['default']
    Theme_button: typeof import('./../components/icon/window_contorl/theme_button.vue')['default']
    Window_close_component: typeof import('./../components/window_close_component.vue')['default']
    Window_maximzie_component: typeof import('./../components/window_maximzie_component.vue')['default']
    Window_minimzie_component: typeof import('./../components/window_minimzie_component.vue')['default']
  }
}
