/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Close_icon: typeof import('./../components/icon/window_contorl/close_icon.vue')['default']
    HomeView: typeof import('./../views/HomeView.vue')['default']
    Maximzie_icon: typeof import('./../components/icon/window_contorl/maximzie_icon.vue')['default']
    Minimzie_icon: typeof import('./../components/icon/window_contorl/minimzie_icon.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NFlex: typeof import('naive-ui')['NFlex']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Theme_button: typeof import('./../components/icon/window_contorl/theme_button.vue')['default']
    Window_close_component: typeof import('./../components/window_close_component.vue')['default']
    Window_maximzie_component: typeof import('./../components/window_maximzie_component.vue')['default']
    Window_minimzie_component: typeof import('./../components/window_minimzie_component.vue')['default']
  }
}
